In [16]:
import numpy as np
from 随书笔记.activateFunction import softmax

a = np.array([0.3,2.9,4.0])
# 指数函数
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [4]:
# 指数函数的和
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [5]:
y = exp_a / sum_exp_a
print(y)


[0.01821127 0.24519181 0.73659691]


In [14]:
a = np.array([1010,1000,990])
c = np.max(a)
print(a-c)
result = np.exp(a-c)/np.sum(np.exp(a-c))
print(result)

[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [17]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]
